# Generated by Django 3.0.4 on 2020-04-15 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0002_auto_20200415_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interfaces',
            old_name='project_id',
            new_name='project',
        ),
    ]
