# Generated by Django 3.0.4 on 2020-05-02 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('interfaces', '0003_auto_20200415_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaces',
            name='id',
            field=models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键'),
        ),
        migrations.AlterField(
            model_name='interfaces',
            name='project',
            field=models.ForeignKey(help_text='所属项目id', on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='projects.Projects'),
        ),
    ]
