# Generated by Django 3.0.4 on 2020-06-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('project_name', models.CharField(help_text='项目名称', max_length=30, unique=True, verbose_name='项目名称')),
                ('leader', models.CharField(help_text='项目经理', max_length=30, verbose_name='项目经理')),
                ('tester', models.CharField(help_text='项目测试人员', max_length=30, verbose_name='项目测试人员')),
                ('programmer', models.CharField(default='小白', help_text='开发人员', max_length=30, verbose_name='开发人员')),
                ('publish_app', models.CharField(default='发布软件', help_text='发布用户名', max_length=30, verbose_name='发布用户名')),
                ('desc', models.CharField(default='简要描述', help_text='简要描述', max_length=255, verbose_name='简要描述')),
                ('is_delete', models.BooleanField(default=True, help_text='删除逻辑', verbose_name='删除逻辑')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
            ],
        ),
    ]
