# Generated by Django 3.0.4 on 2020-04-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('project_name', models.CharField(help_text='项目名称', max_length=30, unique=True, verbose_name='项目名称')),
                ('leader', models.CharField(help_text='项目经理', max_length=30, verbose_name='项目经理')),
                ('tester', models.CharField(help_text='项目测试人员', max_length=30, verbose_name='项目测试人员')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
            ],
        ),
    ]
